### ISSUE TITLE
Wrong score in "Parasite or not"

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/MalariaSmearSearch#195]
When a non-parasite object is highlighted and the "Not a parasite" button is clicked, the error score is incremented. The success score should be incremented instead.

**Comment by nanls** [comment]
Je suis vraiment désolée, mais je n'arrive pas à reproduire le bug. -- ou alors mon cerveau n'est pas encore réveillé -- 
De plus, actuellement le code est : 
```
if (
            // current anno is a para and the user has clicked yes :
            (this.current_anno.annotation[0]==='P' && answer === 'yes')
            // current anno is not a para and the user has clicked no :
            || (this.current_anno.annotation[0]!=='P' && answer === 'no')
        ){
            this.success++;
            $('#success').html(this.success);
        }else{
            this.errors++;
            $('#errors').html(this.errors);
        }
```
Du coup j'ai du mal à comprendre ce qu'il s'est passé pendant votre test.

**Comment by pierrepo** [comment]
Sorry my mistake. I probably did not update the reload the source code properly when I performed my test.

I'll close this issue.
