### ISSUE TITLE
Missing parasite highlight in "Find parasites"

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/MalariaSmearSearch#196]
In the "Find parasites" e-learning activity, the last found parasite is not correctly highlighted with a green box.

**Comment by nanls** [comment]
de même : je n'arrive pas à reproduire le bug. ou alors je ne comprends pas ce que vous voulez dire. :disappointed:

**Comment by pierrepo** [comment]
Sorry probably a mistake.

I close the issue.
