### ISSUE TITLE
Generated data should be in one single place

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/MalariaSmearSearch#197]
To ease maintenance and deploiement, the data generated by users and web app should be in a single directory. For instance `data`. The following files and directories should be found in this directory:

- `data.db`
- `users.db`
- `samples/`
- `chunks/`

MSS app should be modified accordingly.

**Comment by nanls** [comment]
Perhaps user.db should not be in the directory.

**Comment by nanls** [comment]
More globally : you asked me to write a script for data redistribution. Thus, is the data directory really necessary ?

**Comment by pierrepo** [comment]
Yes the data directory is very important to ease the web application maintenance.
`data.db`, `users.db`, `samples/` and `chunks/` should be in the data directory.

The script I asked you to write is for data export to Zenodo.
